version: "3.3"
services:

  hw2:
    container_name: hw2
    depends_on:
      - db-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/results
    networks:
      - backend

  db-service:
    image: linuxserver/mariadb:latest
    container_name: db-service
    restart: always
    volumes:
      - ./db:/config
    networks:
      - backend
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_USER: root # pragma: allowlist secret
      MYSQL_PASSWORD: secret # pragma: allowlist secret
      MYSQL_ROOT_PASSWORD: secret # pragma: allowlist secret
    ports:
      - 3306:3306

networks:
  backend: